name: ${oc.env:PWD}/models/Llama-3.2-1B-eos-sft-template-format-curated-v1-lr2e-6-sample-10
class_name: LlamaForCausalLM
tokenizer_class: LlamaTokenizer
tokenizer_name: ${oc.env:SHARE_RES_DIR}/models/llama3/hf/Llama-3.2-1B
inner_params:
- model.layers.13.mlp.gate_proj.weight
- model.layers.13.mlp.up_proj.weight
- model.layers.13.mlp.down_proj.weight
- model.layers.14.mlp.gate_proj.weight
- model.layers.14.mlp.up_proj.weight
- model.layers.14.mlp.down_proj.weight
- model.layers.15.mlp.gate_proj.weight
- model.layers.15.mlp.up_proj.weight
- model.layers.15.mlp.down_proj.weight