name: ${oc.env:PWD}/models/Llama-3.2-1B-eos-sft
class_name: LlamaForCausalLM
tokenizer_class: LlamaTokenizer
tokenizer_name: ${oc.env:SHARE_RES_DIR}/models/llama3/hf/Llama-3.2-1B
inner_params:
- model.layers.4.mlp.gate_proj.weight
- model.layers.4.mlp.up_proj.weight
- model.layers.4.mlp.down_proj.weight
- model.layers.5.mlp.gate_proj.weight
- model.layers.5.mlp.up_proj.weight
- model.layers.5.mlp.down_proj.weight
- model.layers.6.mlp.gate_proj.weight
- model.layers.6.mlp.up_proj.weight
- model.layers.6.mlp.down_proj.weight
- model.layers.7.mlp.gate_proj.weight
- model.layers.7.mlp.up_proj.weight
- model.layers.7.mlp.down_proj.weight
- model.layers.8.mlp.gate_proj.weight
- model.layers.8.mlp.up_proj.weight
- model.layers.8.mlp.down_proj.weight
- model.layers.9.mlp.gate_proj.weight
- model.layers.9.mlp.up_proj.weight
- model.layers.9.mlp.down_proj.weight
- model.layers.10.mlp.gate_proj.weight
- model.layers.10.mlp.up_proj.weight
- model.layers.10.mlp.down_proj.weight
- model.layers.11.mlp.gate_proj.weight
- model.layers.11.mlp.up_proj.weight
- model.layers.11.mlp.down_proj.weight
- model.layers.12.mlp.gate_proj.weight
- model.layers.12.mlp.up_proj.weight
- model.layers.12.mlp.down_proj.weight
- model.layers.13.mlp.gate_proj.weight
- model.layers.13.mlp.up_proj.weight
- model.layers.13.mlp.down_proj.weight
- model.layers.14.mlp.gate_proj.weight
- model.layers.14.mlp.up_proj.weight
- model.layers.14.mlp.down_proj.weight
- model.layers.15.mlp.gate_proj.weight
- model.layers.15.mlp.up_proj.weight
- model.layers.15.mlp.down_proj.weight