name: ${oc.env:PWD}/models/Llama-3.2-3B-eos-sft-template-format-curated-v1-lr2e-6-sample-10
class_name: LlamaForCausalLM
tokenizer_class: LlamaTokenizer
tokenizer_name: ${oc.env:SHARE_RES_DIR}/models/llama3/hf/Llama-3.2-3B
inner_params:
# - model.layers.13.mlp.gate_proj.weight
# - model.layers.13.mlp.up_proj.weight
# - model.layers.13.mlp.down_proj.weight
# - model.layers.14.mlp.gate_proj.weight
# - model.layers.14.mlp.up_proj.weight
# - model.layers.14.mlp.down_proj.weight
- model.layers.15.mlp.gate_proj.weight
- model.layers.15.mlp.up_proj.weight
- model.layers.15.mlp.down_proj.weight
- model.layers.16.mlp.gate_proj.weight
- model.layers.16.mlp.up_proj.weight
- model.layers.16.mlp.down_proj.weight
- model.layers.17.mlp.gate_proj.weight
- model.layers.17.mlp.up_proj.weight
- model.layers.17.mlp.down_proj.weight
- model.layers.18.mlp.gate_proj.weight
- model.layers.18.mlp.up_proj.weight
- model.layers.18.mlp.down_proj.weight
- model.layers.19.mlp.gate_proj.weight
- model.layers.19.mlp.up_proj.weight
- model.layers.19.mlp.down_proj.weight
- model.layers.20.mlp.gate_proj.weight
- model.layers.20.mlp.up_proj.weight
- model.layers.20.mlp.down_proj.weight
- model.layers.21.mlp.gate_proj.weight
- model.layers.21.mlp.up_proj.weight
- model.layers.21.mlp.down_proj.weight
- model.layers.22.mlp.gate_proj.weight
- model.layers.22.mlp.up_proj.weight
- model.layers.22.mlp.down_proj.weight
- model.layers.23.mlp.gate_proj.weight
- model.layers.23.mlp.up_proj.weight
- model.layers.23.mlp.down_proj.weight
- model.layers.24.mlp.gate_proj.weight
- model.layers.24.mlp.up_proj.weight
- model.layers.24.mlp.down_proj.weight
- model.layers.25.mlp.gate_proj.weight
- model.layers.25.mlp.up_proj.weight
- model.layers.25.mlp.down_proj.weight
- model.layers.26.mlp.gate_proj.weight
- model.layers.26.mlp.up_proj.weight
- model.layers.26.mlp.down_proj.weight
- model.layers.27.mlp.gate_proj.weight
- model.layers.27.mlp.up_proj.weight
- model.layers.27.mlp.down_proj.weight