name: ${oc.env:PWD}/models/Qwen2.5-1.5B-qa-sft-qa-additional
class_name: Qwen2ForCausalLM
tokenizer_class: Qwen2Tokenizer
tokenizer_name: ${oc.env:PWD}/models/Qwen2.5-1.5B-qa-sft-qa-additional
inner_params:
- model.layers.18.mlp.gate_proj.weight
- model.layers.18.mlp.up_proj.weight
- model.layers.18.mlp.down_proj.weight
- model.layers.19.mlp.gate_proj.weight
- model.layers.19.mlp.up_proj.weight
- model.layers.19.mlp.down_proj.weight
- model.layers.20.mlp.gate_proj.weight
- model.layers.20.mlp.up_proj.weight
- model.layers.20.mlp.down_proj.weight
- model.layers.21.mlp.gate_proj.weight
- model.layers.21.mlp.up_proj.weight
- model.layers.21.mlp.down_proj.weight
- model.layers.22.mlp.gate_proj.weight
- model.layers.22.mlp.up_proj.weight
- model.layers.22.mlp.down_proj.weight