alg: enn
lr: 1e-5
edit_lr: 1e-2
seed: 0
debug: False
model_save_pt: 5000
edit_bs: 1
silent: False
max_iters: 1000000
log_interval: 100
val_interval: 5000
lr_lr: 1e-3
batch_size: 2
val_batch_size: 5
accumulate_bs: 10
cedit: 0.1
cloc: 1.0
cbase: 1.0
val_steps: 500
device: cuda:0
base_loss: distill
oracle: False
train: True
train_base: True
opt: Adam
single_batch: False
archive: null
grad_clip: 100.
ref: null
early_stop_patience: 20000
early_stop_key: "loss/total_edit_val"
dropout: 0.0
tokenizer: null
results_dir: null
no_grad_layers: null
eval_only: False
half: False
save: False

l_e_data: rephrase
edit_loss: p(y|x)
edit_input: question

model:
  pt: null

data:
  path: null
  rephrase: true
  musique_propagation_only: false
  zsre_nq: true
  nq_path: ${hydra:runtime.cwd}/data/nq
  wiki_webtext: true
  n_edits: 1

eval:
  verbose: True
  log_interval: 100
  final_eval: True

generation:
  max_new_tokens: 20
  prompt: urial # no
  save_dir: 

hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S_%f${uuid:}}
  sweep:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S_%f}
    subdir: ${hydra.job.num}